platform :ios, '9.0'
use_frameworks!


target 'AsakusaSatelliteSwiftClientExample' do
  pod 'AsakusaSatellite', :path => '../'

  target 'AsakusaSatelliteSwiftClientExampleTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end
end
