platform :ios, '8.0'
use_frameworks!

link_with 'AsakusaSatelliteSwiftClientExample'

pod 'AsakusaSatellite', :path => '../'

target 'AsakusaSatelliteSwiftClientExampleTests' do
    pod 'Quick'
    pod 'Nimble'
end
