platform :ios, '8.0'
use_frameworks!

link_with 'AsakusaSatelliteSwiftClientExample', 'AsakusaSatelliteSwiftClientExampleTests'

pod 'AsakusaSatellite', :path => '../'

# TODO: remove after they're published to the spec repo
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode7'
pod 'Socket.IO-Client-Swift', :git => 'https://github.com/socketio/socket.io-client-swift.git', :branch => 'swift-2'
pod 'UTIKit', :git => 'https://github.com/banjun/UTIKit.git', :branch => 'xcode7'

